BREED_OPTIONS: dict[str, list[str]] = {
    "dog": [
        "Labrador Retriever",
        "German Shepherd",
        "Golden Retriever",
        "French Bulldog",
        "Bulldog",
        "Poodle",
        "Beagle",
        "Rottweiler",
        "Yorkshire Terrier",
        "Dachshund",
        "Siberian Husky",
        "Boxer",
        "Shih Tzu",
        "Great Dane",
        "Chihuahua",
        "Border Collie",
        "Maltese",
        "Cocker Spaniel",
        "Doberman Pinscher",
        "Mixed / Other",
    ],
    "cat": [
        "Persian",
        "Maine Coon",
        "Siamese",
        "Ragdoll",
        "Bengal",
        "British Shorthair",
        "Sphynx",
        "Scottish Fold",
        "Abyssinian",
        "American Shorthair",
        "Norwegian Forest Cat",
        "Domestic Shorthair",
        "Mixed / Other",
    ],
    "rabbit": [
        "Holland Lop",
        "Mini Rex",
        "Netherland Dwarf",
        "Lionhead",
        "Flemish Giant",
        "French Lop",
        "Rex",
        "Dutch",
        "English Spot",
        "American",
        "Mixed / Other",
    ],
    "bird": [
        "Parakeet / Budgerigar",
        "Cockatiel",
        "African Grey Parrot",
        "Macaw",
        "Conure",
        "Lovebird",
        "Canary",
        "Finch",
        "Cockatoo",
        "Amazon Parrot",
        "Eclectus Parrot",
        "Mixed / Other",
    ],
    "other": [
        "Guinea Pig",
        "Hamster",
        "Gerbil",
        "Ferret",
        "Turtle / Tortoise",
        "Bearded Dragon",
        "Gecko",
        "Corn Snake",
        "Ball Python",
        "Mixed / Other",
    ],
}
